### ISSUE TITLE
where can I find class_hierarchy.json

### ISSUE THREAD

**Issue by abhidipbhattacharyya** [nocaps-org/updown-baseline#17]
Hello,

Where can I find class_hierarchy.json? From the documentation I got the following:

DATA.CBS.CLASS_HIERARCHY: "data/cbs/class_hierarchy.json"
        Path to a JSON file containing a hierarchy of Open Images object classes as
        `here <https://storage.googleapis.com/openimages/2018_04/bbox_labels_600_hierarchy_visualizer/circle.html>`

Though this one is a nice visualization but this is not the json file. Please help.

regards,
Abhidip

**Comment by kdexd** [comment]
Hi @abhidipbhattacharyya  — [here's the download link](https://storage.googleapis.com/openimages/2018_04/bbox_labels_600_hierarchy.json) from the [official Open Images dataset page](https://storage.googleapis.com/openimages/web/download.html).

**Comment by abhidipbhattacharyya** [comment]
Thank you.
