### ISSUE TITLE
Mismatch dimensions between pretrained file and code

### ISSUE THREAD

**Issue by Xiaoming-Zhao** [nocaps-org/updown-baseline#7]
Hi, thanks a lot for this great dataset. I just followed the steps from [How to setup this codebase?](https://nocaps.org/updown-baseline/setup_dependencies.html#) and wanted to test the baseline on the validation / test dataset. However, there exist mismatches between the pretrained models and the code. Could you please verify it? Thanks!

```
RuntimeError: Error(s) in loading state_dict for UpDownCaptioner:
	Missing key(s) in state_dict: "_output_layer.bias".
	Unexpected key(s) in state_dict: "to_glove.weight", "to_glove.bias".
	size mismatch for _embedding_layer.weight: copying a param with shape torch.Size([10622, 300]) from checkpoint, the shape in current model is torch.Size([10315, 1000]).
	size mismatch for _updown_cell._attention_lstm_cell.weight_ih: copying a param with shape torch.Size([4800, 4748]) from checkpoint, the shape in current model is torch.Size([4800, 5448]).
	size mismatch for _output_layer.weight: copying a param with shape torch.Size([10622, 300]) from checkpoint, the shape in current model is torch.Size([10315, 1200]).
```

**Comment by kdexd** [comment]
Oops, looks like a variable name mismatch from an older commit. I'll fix this.

Thanks for reporting!

**Comment by kdexd** [comment]
@Xiaoming-Zhao could you share the exact command you tried?

More specifically, what pair of config file + checkpoint URL did you use?

**Comment by kdexd** [comment]
Fixed the checkpoint path, thanks!
